import type { Env } from '../types';
import type { NormalizedReservationInput, ReservationListFilters, ReservationLogStatus, ReservationPublicSummary, ReservationRecord, ReservationStatus } from './types';
type InsertReservationParams = NormalizedReservationInput & {
    id: string;
    reservationCode: string;
    googleCalendarEventId?: string | null;
    status?: ReservationStatus;
    requestIp?: string | null;
    userAgent?: string | null;
};
export declare const toPublicSummary: (record: ReservationRecord) => ReservationPublicSummary;
export declare const findReservationByCode: (env: Env, reservationCode: string) => Promise<ReservationRecord | null>;
export declare const insertReservation: (env: Env, reservation: InsertReservationParams) => Promise<{
    googleCalendarEventId: string | null;
    status: ReservationStatus;
    createdAt: string;
    updatedAt: string;
    customerFullName: string;
    reservationForType: import("./types").ReservationForType;
    reservedPersonName: string | null;
    guestCount: number;
    guestCountMode: import("./types").GuestCountMode;
    hasChildren: boolean;
    dietaryRestrictionType: import("./types").DietaryRestrictionType;
    dietaryRestrictionNotes: string | null;
    seatingPreference: import("./types").SeatingPreference;
    whatsappNumber: string;
    email: string | null;
    reservationTime: import("./types").ReservationTime;
    reservationDate: string;
    mealPeriod: import("./types").MealPeriod;
    isExistingCustomer: boolean;
    discoverySource: import("./types").DiscoverySource | null;
    notes: string | null;
    tolerancePolicyText: string;
    id: string;
    reservationCode: string;
    requestIp?: string | null;
    userAgent?: string | null;
}>;
export declare const updateReservationCalendarEvent: (env: Env, reservationId: string, googleCalendarEventId: string) => Promise<void>;
export declare const updateReservationStatus: (env: Env, reservationId: string, status: ReservationStatus) => Promise<void>;
export declare const insertReservationLog: (env: Env, reservationId: string, eventType: string, status: ReservationLogStatus, details: Record<string, unknown>) => Promise<void>;
export declare const listReservations: (env: Env, filters: ReservationListFilters) => Promise<ReservationRecord[]>;
export {};
